---
version: "3.3"

services:
  potber-api-develop:
    image: 'spuxx/potber-api:develop-latest'
    restart: always
    networks:
      - default
      - npm
    env_file:
      .env
    command: npm run start:prod

networks:
  default:
  npm:
    external: true
