name: staging

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  types:
    uses: spuxx1701/ci-cd/.github/workflows/npm_types.yml@v4.1.0

  lint:
    uses: spuxx1701/ci-cd/.github/workflows/npm_lint.yml@v4.1.0

  test:
    uses: spuxx1701/ci-cd/.github/workflows/npm_test-coverage.yml@v4.1.0

  release_image:
    needs:
    - types
    - lint
    - test
    uses: spuxx1701/ci-cd/.github/workflows/docker_release_image.yml@v4.1.0
    secrets:
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
